title: Test GitPage
author: RGacesa
email: rgacesa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Test page
# social links
twitter_username: rgacesa # DO NOT include the @ character, or else the build will fail!
github_username:  rgacesa # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
